"""
Generate a synthetic NIFTY + VIX cache so the pipeline can be exercised before
real Kite data is available. NOT for research — the price process is a toy
(random walk + intraday trend + noise). Results on synthetic data are
meaningless; this only proves the plumbing works.

    python -m backtest.data.synth --days 120
"""

from __future__ import annotations

import argparse
from datetime import date, datetime, timedelta

import numpy as np
import pandas as pd

from . import CACHE_DIR

SESSION = [(9, 15), (15, 30)]


def _session_stamps(d: date):
    start = datetime(d.year, d.month, d.day, *SESSION[0])
    end = datetime(d.year, d.month, d.day, *SESSION[1])
    out, t = [], start
    while t < end:
        out.append(t)
        t += timedelta(minutes=5)
    return out


def gen(days: int, seed: int = 7):
    rng = np.random.default_rng(seed)
    end = date.today()
    d = end - timedelta(days=days)
    px = 24000.0
    vix = 13.0
    rows, vrows = [], []
    while d <= end:
        if d.weekday() < 5:
            drift = rng.normal(0, 0.0012)                 # daily trend bias
            for ts in _session_stamps(d):
                step = rng.normal(drift / 75, 0.0009)
                px *= (1 + step)
                rng_pts = abs(rng.normal(0, 6)) + 2
                o = px
                c = px * (1 + rng.normal(0, 0.0004))
                hi = max(o, c) + rng.random() * rng_pts
                lo = min(o, c) - rng.random() * rng_pts
                rows.append((ts, o, hi, lo, c, int(rng.integers(1e5, 9e5))))
                px = c
                vix = float(np.clip(vix + rng.normal(0, 0.15), 8, 32))
                vrows.append((ts, vix, vix, vix, vix, 0))
        d += timedelta(days=1)

    idx = pd.DataFrame(rows, columns=["date", "open", "high", "low", "close", "volume"])
    vx = pd.DataFrame(vrows, columns=["date", "open", "high", "low", "close", "volume"])
    vxd = (vx.set_index("date")["close"].resample("1D").agg(["first", "max", "min", "last"])
           .dropna().reset_index())
    vxd.columns = ["date", "open", "high", "low", "close"]
    vxd["volume"] = 0

    idx.to_parquet(CACHE_DIR / "nifty_5minute.parquet", index=False)
    vx.to_parquet(CACHE_DIR / "vix_5minute.parquet", index=False)
    vxd.to_parquet(CACHE_DIR / "vix_day.parquet", index=False)
    # crude futures = index + tiny basis
    fut = idx.copy()
    for col in ("open", "high", "low", "close"):
        fut[col] = fut[col] + 8.0
    fut.to_parquet(CACHE_DIR / "nifty_fut_5minute.parquet", index=False)
    (CACHE_DIR / "_SYNTHETIC.flag").write_text(
        f"Cache generated by synth.py on {datetime.now():%Y-%m-%d %H:%M}. "
        "Toy random-walk data — results are NOT real. "
        "Delete this flag + rerun backtest.data.fetch for real data.\n"
    )
    print(f"wrote {len(idx):,} index bars, {len(vx):,} vix bars to {CACHE_DIR}")
    print("⚠  SYNTHETIC data — backtest results will be meaningless until you fetch real data.")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=120)
    ap.add_argument("--seed", type=int, default=7)
    a = ap.parse_args()
    gen(a.days, a.seed)
